#! /usr/bin/env ruby
require "irb"
require File.join(File.dirname(__FILE__), '..', 'castronaut')

Castronaut.config = Castronaut::Configuration.load(File.join(File.dirname(__FILE__), '..', 'castronaut.yml'))

IRB.start(__FILE__)
